name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - backend/**


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::273711029273:role/DeployFrontEndTestOIDC
        role-session-name: DeployFrontendSession
        aws-region: eu-central-1    
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5
    - name: Deploy infrastructure
      run: terraform apply -auto-approve
      working-directory: ./ReactLambda/terraform
