name: Deploy Backend Go

on: workflow_dispatch



permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#      with:
#        repository: chrisxue815/realworld-aws-lambda-dynamodb-go  
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::273711029273:role/DeployBackEndTestOIDC
        role-session-name: DeployFrontendSession
        aws-region: eu-central-1    
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15
    - name: Make executeable
      run: chmod +x ./gobuild.sh
      working-directory: ./ReactLambda/backend-go
    - name: Make executeable
      run: chmod +x ./gomod.sh
      working-directory: ./ReactLambda/backend-go
    - name: build application
      run: make build  
      working-directory: ./ReactLambda/backend-go
    - run: TF_LOG=DEBUG terraform init
      working-directory: ./ReactLambda/terraform/staging/services/backend
    - id: plan
      run: terraform apply -auto-approve
      working-directory: ./ReactLambda/terraform/staging/services/backend
